services:
  db:
    build: ./db
    container_name: mysql-server
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    container_name: fastapi-server
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: nextjs-server
    depends_on:
      - backend
    ports:
      - "3000:3000"